### ISSUE TITLE
Parse errors

### ISSUE THREAD

**Issue by jonaprieto** [banacorn/agda-mode#100]
Hi, 

I'm having some many parsing errors like this one with different already type-checked files.
Sometimes happens but not always. I'm using Agda 2.6.0. Is this version supported?

![image](https://user-images.githubusercontent.com/1428088/60027260-6e88c600-969d-11e9-9390-3c0607c3fe22.png)

![image](https://user-images.githubusercontent.com/1428088/60027730-46e62d80-969e-11e9-983a-c68e4d0e4206.png)

And another issue is when it gets stuck while type-checking some codes.
I'm sorry, this time I couldn't find the MBPs, but I'm sure these need attention. hehe
Maybe this is something about my installation? I don't know.

**Comment by banacorn** [comment]
Thank you for reporting this!
There's nothing's wrong about your installation. (However, you might will want to upgrade from `Agda-2.6.0` to `Agda-2.6.0.1`)
I've found a glitch in the parsing and fixed it, the patch is on the way!

**Comment by banacorn** [comment]
Please reopen this issue if the problem persists

**Comment by jonaprieto** [comment]
The holes are not showing up. They keep the question mark, any reason?

PD. I updated the Agda version.

**Comment by banacorn** [comment]
@jonaprieto sorry for the inconvenience, did that parse error occurred again after you've upgraded to `v0.9.3`?

Is the holes not showing up thing related to the previous parsing issue, or another issue of its own?

**Comment by jonaprieto** [comment]
> @jonaprieto sorry for the inconvenience, did that parse error occurred again after you've upgraded to `v0.9.3`?
Yes, it did. 
> 
> Is the holes not showing up thing related to the previous parsing issue, or another issue of its own?
I might say yes, it is a different issue, but I'm not sure. Btw, it seems the holes in comments are also being active, you can jump to them with ctrl+c+f.

**Comment by banacorn** [comment]
@jonaprieto  I see, could you please open another issue for the holes? (Also it would be nice to attach a example Agda file for reproducing the issue).
I'm closing this issue to mark the parse errors solved.
