### ISSUE TITLE
Error linking agda on windows

### ISSUE THREAD

**Issue by Totoro83** [banacorn/agda-mode#110]
Using agda-mode 0.9.7 and atom 1.40.1 on windows, entering the full path of agda (in my case C:\Users\Totoro\AppData\Roaming\cabal\bin\agda.exe), I get the following error message:

```
Error: Error from the shell

error message:

Error: Command failed: C:/Users/Totoro/AppData/Roaming/cabal/bin/agda.exe
```

Agda works (or at least it seems so) and if I try to execute that command, both in power shell that in command prompt, it shows the correct agda usage help.

**Comment by banacorn** [comment]
Sorry I still cannot reproduce this, which version of Windows are you using?

**Comment by odomanov** [comment]
I can confirm the bug on Windows 10 -- the same error message. On the same machine, Emacs agda-mode works fine.

**Comment by odomanov** [comment]
It seems that this advice helps:
https://github.com/banacorn/agda-mode/issues/97#issuecomment-491516453
I'm not sure about possible side effects though.

**Comment by banacorn** [comment]
@odomanov thank you, I've updated the README for the posterity
@totoro83 does https://github.com/banacorn/agda-mode/issues/97#issuecomment-491516453 work for you?

**Comment by odomanov** [comment]
Unfortunately, this Windows feature is Beta and so can create problems. I've already run into a program (WikidPad) that stopped working. Is it possible to fix this in Atom?

**Comment by banacorn** [comment]
Yes, I think I can do something about this.
At least we can bypass #97 and see what would happen next.

**Comment by banacorn** [comment]
Yes, I think I can do something about this.
At least we can bypass #97 and see what would happen next.
