### ISSUE TITLE
C-c C-a doesnt call auto, instead calls refine.

### ISSUE THREAD

**Issue by Zinfour** [banacorn/agda-mode#112]
Agda version 2.6.1-5b74cc2
agda-mode 0.9.7

**Comment by banacorn** [comment]
Good lord, I've been wondering why auto doesn't seem to work for a while  

＊facepalm＊
https://github.com/banacorn/agda-mode/blob/0debb886eb5dbcd38dbeebd04b34cf9d9c5e0e71/src/Instance/Instance__Handler.re#L526-L530

Thank you for reporting this!
