### ISSUE TITLE
Auto search uses Intro

### ISSUE THREAD

**Issue by MarcelineVQ** [banacorn/agda-mode#117]
Working on [plfa](https://plfa.github.io/Relations/) I noticed that auto-search wasn't operating correctly.
When tring to fill the singular hole below, C-c C-a results in the exact same output as C-c C-r for me, namely
```
Intro

No introduction forms found.
```
Based on what I could understand of the agda-mode source code this should say Auto not Intro? Regardless it doesn't plug the hole and I had someone use C-c C-a in emacs and they were able to plug the hole.
My keybindings are correctly resolving C-c C-a to agda-mode:auto, and using agda-mode:auto via the toolbar menu Packages->Agda Mode->Auto still has the same output.

Code used to notice issue:
```
module plfa.part1.Relations where

import Relation.Binary.PropositionalEquality as Eq
open Eq using (_≡_; refl; cong)
open import Data.Nat using (ℕ; zero; suc; _+_)
open import Data.Nat.Properties using (+-comm)

infix 4 _≤_

data _≤_ : ℕ → ℕ → Set where
  z≤n : ∀ {n : ℕ} → zero ≤ n
  s≤s : ∀ {m n : ℕ} → m ≤ n → suc m ≤ suc n

data Total (m n : ℕ) : Set where
  forward : m ≤ n → Total m n
  flipped : n ≤ m → Total m n

≤-total : ∀ (m n : ℕ) → Total m n
≤-total zero n = forward z≤n
≤-total (suc m) zero = flipped z≤n
≤-total (suc m) (suc n) with ≤-total m n
...                        | forward m≤n = forward (s≤s {!   !})
...                        | flipped n≤m = flipped (s≤s n≤m)
```

**Comment by MarcelineVQ** [comment]
I'm an idiot, just needed to update.

**Comment by banacorn** [comment]
Yes, `C-c C-a` should be working now, your highness.
