### ISSUE TITLE
go-to-definition input howto

### ISSUE THREAD

**Issue by pnlph** [banacorn/agda-mode#118]
I want to know where an imported operation was defined, but i cannot use the go-to-definition command with agda-mode in Atom.

From the documentation, the keymap should be:
<kbd>C-alt-\\</kbd> or <kbd>alt-cmd-\\</kbd> 

But i get the backslash itself with a combination:
<kbd>shift-alt-7</kbd>

How is the input of a combination of three keys when one of them is another combination of three keys?

Another issue is that i do not see the go-to-definition command in the menu `Packages -> Agda mode`

Atom 1.42.0 x64
agda-mode 0.9.10

**Comment by banacorn** [comment]
You can [customize keybindings](https://flight-manual.atom.io/using-atom/sections/basic-customization/#customizing-keybindings) to replace the backslash.

Yes, thank you, I should put the go-to-definition command in the menu!

**Comment by pnlph** [comment]
Thank you, it works. In case someone else needs it, just take eg. <kbd>alt-cmd-\\</kbd>, paste the following to the keybindings and replace:

```
'.platform-darwin atom-text-editor[data-grammar~="agda"]':
  'alt-cmd-\': 'agda-mode:go-to-definition'
```
