### ISSUE TITLE
Goal numbers are floating

### ISSUE THREAD

**Issue by TheoWinterhalter** [banacorn/agda-mode#14]
The numbers of goals (like in `{! 1}`) get over the gui as you can see.

![capture d ecran 2015-05-27 a 10 15 43](https://cloud.githubusercontent.com/assets/5960860/7831728/c0650108-0459-11e5-970a-1b0cb8ecc94f.png)
![capture d ecran 2015-05-27 a 10 18 50](https://cloud.githubusercontent.com/assets/5960860/7831735/d03f7dec-0459-11e5-8372-abf452368c43.png)

I guess the problem comes from the extra CSS.

**Comment by banacorn** [comment]
I'm afraid those floating numbers are not going away anytime soon :sob:  

In the previous versions, the physical representation of goals was made with some direct and brutal DOM manipulation, which will be [deprecated and removed on June 1st] (http://blog.atom.io/2015/05/01/removing-deprecated-apis.html) (addressed by issue #12 )

Now the representation is rewritten with [Decoration API] (https://atom.io/docs/api/v0.201.0/TextEditor#instance-decorateMarker).
There are 4 types of decorations: `line`, `gutter` `highlight` (for blue background) and `overlay` (for orange goal index).  Overlays are floaty by its nature, but I can't seem to push it down by setting the `z-index` :cry: 

Hope they will add more types of decoration in the future

**Comment by iSheeft** [comment]
Oh I see, that's too bad then.

Well, it is not really a big deal so it can wait for future API.
