### ISSUE TITLE
Give does not replace

### ISSUE THREAD

**Issue by zenzike** [banacorn/agda-mode#15]
It seems that using give does not replace the content of a hole with a well-typed term when the term is a `String`. All that happens is a type-check, but no replacement. Works fine when I tried with a `Nat`.

 This doesn't work when using either `Ctrl-c Ctrl-space` or `Agda Mode: Give`.

**Comment by banacorn** [comment]
Patched in `v0.2.21`, failed to escape double qoutes `"`.
