### ISSUE TITLE
Cannot do "case" 

### ISSUE THREAD

**Issue by scmu** [banacorn/agda-mode#16]
With this sample file

```
module AtomTst where

open import Data.Product

f : {A B : Set} → (A × B) → A
f x =  ?
```

when the cursor is in the hole and when I type ctrl-c ctrl-c, I got this error message:

```Cannot split on result here
when checking that the expression ? has type .A```

In some other cases I got error message about co-pattern splitting. It seems that Agda thought I issued a different command.

**Comment by banacorn** [comment]
That's because Agda has no idea which pattern variables to case, and you'll have to provide one by putting it in the hole. 

But I've never done any co-pattern splitting before, maybe that's another issue, could you provide a sample file about this?

**Comment by scmu** [comment]
I see. I've always entered the variable to case after Ctrl-c-c, hence the confusion. Casing works if I specify the variable first. 

Thanks! I think we can consider this issue closed.

**Comment by banacorn** [comment]
In Emacs, if the hole is left empty when casing, agda-mode would pop a input box and ask you to fill it. 
I'll close this issue after adding it to Atom.

**Comment by banacorn** [comment]
`v0.3.2`
