### ISSUE TITLE
Wish: goal and environment types with full normalisation

### ISSUE THREAD

**Issue by scmu** [banacorn/agda-mode#17]
With this sample file:

```
module AtomTst where

open import Data.Product

Pair : Set → Set
Pair A = A × A

f : {A : Set} → Pair A → A
f = {!   !}
```

The behaviour in the Agda mode in Emacs is that
* if you type `ctrl-u-c-,`, the type of the goal is displayed as `{A : Set} → Pair A → A`,
* if you type `ctrl-u-u-c-,`  the type of the goal is `{A : Set} → Σ A (λ x → A) → A`.
It seems that this Atom mode currently supports only the former.

Curiously, `ctrl-u-u-c-,` is not mentioned on the official wiki:
http://wiki.portal.chalmers.se/agda/pmwiki.php?n=Docs.EmacsModeKeyCombinations
But it turns out to be very useful for many. It was only discussed in a thread starting from May 2013
https://code.google.com/p/agda/issues/detail?id=850
where it was suggested to use the key-bindings:

*         C-c C-t for simpl
*     C-u C-c C-t for no normalization
* C-u C-u C-c C-t for full normalization

And in June 2014 they adopted this convention.

**Comment by banacorn** [comment]
This is that I found in [the source](
https://github.com/agda/agda/blob/344296cf06cedd13736e50bb53e63217d9f19ecf/src/full/Agda/Interaction/BasicOps.hs#L210
) of Agda:
``` haskell
data Rewrite =  AsIs | Instantiated | HeadNormal | Simplified | Normalised
    deriving (Read)
```

This is how they correspond to the commands:

| keymap | command | `Rewrite` |
|----------------|----|------------------------|
|         `C-c C-t` | simpl | Simplified |
|     `C-u C-c C-t` | no normalization | Instantiated |
|  `C-u C-u C-c C-t` | full normalization | Normalised |
|  `?` | ? | AsIs |
|  `?` | ? | HeadNormal |

interesting ... :octopus:

**Comment by banacorn** [comment]
`v0.3.1` now have "something in between"
