### ISSUE TITLE
goal content is parsed incorrectly

### ISSUE THREAD

**Issue by markokoleznik** [banacorn/agda-mode#20]
This example gives me Parse error. I'm quite sure it's because `\n` character inside that goal, which stands for λ in Agda I believe.  Try it in Emacs, you should get normal result when refining that goal. (`ctrl-c ctrl-r`)
```
module Foo where

 data ℕ : Set where
   zero : ℕ
   succ : ℕ → ℕ

 data Ordinal : Set where
   zer : Ordinal
   suc : Ordinal → Ordinal
   sup : (ℕ → Ordinal) → Ordinal

 sum : Ordinal → Ordinal → Ordinal
 sum zer y = y
 sum (suc x) y = suc (sum x y)
 sum (sup xs) y = {! \n → sup !}
```
Btw, I'm using 0.3.7 version of agda-mode.

**Comment by banacorn** [comment]
Issue reproduced!

What Emacs's sent: `" \\n \x2192\& sup  "`
What Atom's sent: `"\n → sup"`

`→` is okay, but `\n` is not.

This is my new string escape policy:
```coffee
rawString
    .replace(/\\/g, '\\\\')    # escape escape character, \ → \\
    .replace(/\"/g, '\\"')    # escape, " → \"
```

Thanks for reporting this and hope that I'm doing it right this time
