### ISSUE TITLE
Displayed types of holes interleaved with each other

### ISSUE THREAD

**Issue by scmu** [banacorn/agda-mode#23]
Please see the attached file. The red parts are the type of hole 0, while the yellow part is the type of hole 1. They are not displayed correctly.

![screen shot 2015-10-14 at 11 55 19 am](https://cloud.githubusercontent.com/assets/11384501/10474720/a0990636-726c-11e5-98c3-6507eedd6860.jpg)

**Comment by banacorn** [comment]
I can't seem to reproduce the issue, could you please provide an example code that I can load against, thanks! :D

**Comment by banacorn** [comment]
The bug is back (It never went away 😂 😂 😂)

[Agda file to reproduce](http://flolac.iis.sinica.edu.tw/flolac16/files/3-Logic.agda)
