### ISSUE TITLE
utf8 input doesn't work since 0.4.5

### ISSUE THREAD

**Issue by aphorisme** [banacorn/agda-mode#27]
I've just updated to 0.4.5; seems as if the \\{input} doesn't work any longer. Rebinding it to a different key (ctrl-i) doesn't fix it. Invoking it directly just inserts a \\.

Is it a bug or is it me?  ; )

**Comment by banacorn** [comment]
Issue reproduced, thanks for reporting this!
Emergency patch is on the way.

**Comment by aphorisme** [comment]
Thanks a lot, works fine.
