### ISSUE TITLE
Input sequences that contain "\", "(" or "{" don't work correctly

### ISSUE THREAD

**Issue by demin-dmitriy** [banacorn/agda-mode#34]
Input mode have some problems with sequences containing `\` `{` `(`. Most of them either don't work or show incorrect symbol when typing them using keyboard (but if i use mouse to click buttons on bottom pane it works just fine)

All of these input prefixes don't work:
* `\d{`
* `\u{`
* `\c{`
* `\d\`
* `\^\`
* `\^{`
and so on.

This sequence shows incorrect symbol
* `\^(`  shows ⁾

**Comment by banacorn** [comment]
Issue reproduced, thanks for reporting this.

Seems like the [Bracket Matcher package](https://atom.io/packages/bracket-matcher) is getting in the way. 

Somehow we need to disable that package during the input.

**Comment by demin-dmitriy** [comment]
@banacorn you are most likely correct about opening brackets, but there is also backslash in keybindings like `\^\alpha` (produces `ᵅ`). My random guess is that there is a bug in this code:

````
export default class InputMethod {
    ...
   activate() {
        if (!this.activated) {
            ...
        } else {
            // input method already activated
            // this will happen when the 2nd backslash '\' got punched in
            // we shall leave 1 backslash in the buffer, then deactivate
            this.deactivate();
        }
````

**Comment by banacorn** [comment]
Now we have another bug :sob:

**Comment by banacorn** [comment]
Disabling the _Bracket Matcher_ and then re-enabling it back doesn't work, and Atom's API also cannot tell which key was pressed. All I can do is hardwired them all to the Keymap :smiling_imp:

`{`, `[`, `{`, `"`, `'`, and `

These 6 keys are now protected from the _Bracket Matcher_.
