### ISSUE TITLE
Please share the path of your agda executable here

### ISSUE THREAD

**Issue by banacorn** [banacorn/agda-mode#40]
Currently on *nix we use `which agda` to locate the path, but it doesn't always work. 
On Windows, we have to query the user about the path upon first installation.

We wish to improve the user experience and make `agda-mode` works out of the box.
To do so, we need to curate a list of paths where `agda` may be installed.

If you are willing to help us, please share the following information with us:

1. The path of the agda executable.
2. The OS you are using (Linux / Mac OS X / Windows ...)
3. The way of installation (via `cabal install`, with installer, build from source, ...)

Thanks :D

**Comment by subttle** [comment]
1. /Users/user/.local/bin/agda
2. OS X
3. `stack install Agda`

I'm regularly using Agda from Stackage LTS.

Thank you for all the work you do!

**Comment by sgraf812** [comment]
1. %APPDATA%\Roaming\local\bin\
2. Windows 10
3. `stack install Agda`

**Comment by rjstone** [comment]
1. C:\Users\Robert\AppData\Roaming\cabal\bin\agda.exe
2. Windows 10
3. `cabal install Agda`

**Comment by freedan42x** [comment]
1. %appdata%\local\bin\
2. Windows 10
3. `stack install Agda`

**Comment by mietek** [comment]
1. `/usr/local/bin/agda`
2. macOS 10.14.6
3. `brew install agda`

**Comment by zraffer** [comment]
1. `~/.local/bin/agda`
2. `Fedora 30 x64` as well as `Ubuntu 19.04`
3. `stack install` after `git clone ...`

**Comment by banacorn** [comment]
Thank you all! I'm closing this because we should have all major platforms covered for detecting the path automatically
