### ISSUE TITLE
Support compute normal form in Agda 2.6

### ISSUE THREAD

**Issue by banacorn** [banacorn/agda-mode#41]
The protocol has changed in Agda-2.6
https://github.com/banacorn/agda-mode/wiki/Conversations-between-Agda-&-agda-mode

**Comment by ruhatch** [comment]
So for normalisation outside a goal we now have

      | Cmd_compute_toplevel B.ComputeMode
                         String

And inside the goal we have

      | Cmd_compute         B.ComputeMode
                        InteractionId range String

Where ComputeMode is defined as

    data ComputeMode = DefaultCompute | IgnoreAbstract | UseShowInstance
  deriving (Read, Eq)

**Comment by banacorn** [comment]
Thanks for pointing the problem out.
I have tested sending this to Agda and it works in the version 2.6
```
IOTCM "/some/path/to/file.agda" None Indirect (Cmd_compute_toplevel DefaultCompute "some expression")
```

**Comment by banacorn** [comment]
I think [these](http://agda.readthedocs.io/en/latest/tools/emacs-mode.html#global-commands) are the commands that correspond to `ComputeMode`. They are:

* <kbd>C-c C-n</kbd>: Compute normal form `DefaultCompute`
* <kbd>C-u C-c C-n</kbd>: Compute normal form, ignoring abstract `IgnoreAbstract`
* <kbd>C-u C-u C-c C-n</kbd>: Compute and print normal form of show <expression> `UseShowInstance`

Prior to 2.6 there were only `DefaultCompute` and `IgnoreAbstract` so it was represented with a `Bool`.

@markokoleznik you may want to look at this, they are messing with the protocol again 😂.

**Comment by ruhatch** [comment]
Thanks for fixing that up! Do you have an ETA for when this might hit stable release? Just wondering whether to install the dev version.

**Comment by banacorn** [comment]
I haven't had the chance to do much testing (it's still mostly manual 😭), but I think it's good to go. What could possibly go wrong?? 😬
