### ISSUE TITLE
Cannot input character "∎" (U+220E END OF PROOF)

### ISSUE THREAD

**Issue by SelectricSimian** [banacorn/agda-mode#45]
The character "∎" (U+220E END OF PROOF) is necessary to end equational reasoning blocks, but there is no ASCII input sequence to type this character using `agda-mode`.  It appears that the emacs version of `agda-mode` uses `\qed` for this purpose.  Would it be possible for this package to do the same?

**Comment by banacorn** [comment]
@danilkolikov has also addressed this in #44 earlier this week.

After some investigation, I found that, along with 5 other symbols (`\geq`, `\leq`, `\bullet`, `\qed`, `par` and `newline`), they were all excluded by the [keymap generator](https://github.com/banacorn/Folge) for some reason I have yet to recall XD
