### ISSUE TITLE
Improve automatic proof search by supporting options

### ISSUE THREAD

**Issue by andrevidela** [banacorn/agda-mode#50]
When using emacs it is possible to change the behaviour of c-c c-a to get more information about the search. 

This document lists all the options that can be put inside a hole to modify the behaviour of c-c c-a 
https://github.com/agda/agda/blob/master/doc/user-manual/tools/auto.rst

It would be nice if agda-mode supported those options as well.

**Comment by banacorn** [comment]
Thanks a lot!

I simply changed a line of code from this:
```typescript
core.view.set('Auto', ['No solution found'], View.Style.Info);
```
to this:
```typescript
core.view.set('Auto', response.content, View.Style.Info);
```
**voilà!**

It turned out that I have been ignoring Agda ever since.
