### ISSUE TITLE
Type error on hole-related operations

### ISSUE THREAD

**Issue by aochagavia** [banacorn/agda-mode#51]
## Version information

OS: Windows 10 x64
Atom: 1.20.1
Electron: 1.6.9
Chrome: 56.0.2924.87
Node: 7.4.0
agda-mode: 0.7.2
language-agda: 0.2.5

## Problem

When using holes, the refine (`C-c C-r`) and auto (`C-c C-a`) commands don't work. Both result in a TypeError from Atom: `Cannot read property 'core' of undefined`. This seems to be an internal error of the `agda-mode` package.

Other commands like `C-c C-l` are working all right.

## How to trigger the error

Use the following program and try 

```agda
module test where

-- Prelude --

data Nat : Set where
  Zero : Nat
  Succ : Nat -> Nat

data _==_ {a : Set} (x : a) : a -> Set where
  Refl : x == x

cong : {a b : Set} {x y : a} -> (f : a -> b) -> x == y -> f x  == f y
cong f Refl = Refl

trans : {a : Set} {x y z : a} -> x == y -> y == z -> x == z
trans Refl q = q

sym : {a : Set} {x y : a} -> x == y -> y == x
sym Refl = Refl

-- Examples
testEq : {x y : Nat} -> x == y -> Succ x == Succ y
testEq proof = cong Succ ?
```

It is clear that the hole in `testEq` should be filled with `proof`. However, even after entering the text `proof`, an attempt to refine results in the error I describe above.

## Stack trace

I would like to include a stack trace, but I don't know how to get a stack trace from Atom, so sorry for that.

**Comment by banacorn** [comment]
Thank you for reporting this!
I've rewritten much of the internals recently and the problem seems to have gone away.
Pplease upgrade your agda-mode to the latest version (v0.7.3) and see if the issue still persists.

**Comment by aochagavia** [comment]
Thanks! I am now getting errors when trying to use case split (`C-c C-c`) and auto  (`C-c C-a`). Maybe there is more, but I haven't tested other commands.

**Comment by banacorn** [comment]
Is it the same error message again? 
I can't seem to reproduce the error :(

There's a way see the stack trace by opening the devtool (right click -> inspect element) that comes with Chromium as part of Atom.
Could you please show me the stack trace and also the version of Agda you are using, thank you!

**Comment by banacorn** [comment]
I don't have access to any computer with internet connection now (I'm currently in some freakin "barrack" 😂), but I guess it may have something to do with what this commit is trying to fix:

https://github.com/banacorn/agda-mode/commit/64af9ebe4490225072adef12bab3e4072a7b88f2

**Comment by aochagavia** [comment]
Thanks for your help. Don't feel any pressure to fix the bugs though. I will keep using emacs in the meantime.

Below are a couple of errors you may find interesting.

# Errors in auto

Errors autocompleting were triggered by the code below:

```agda
data Nat : Set where
  Zero : Nat
  Succ : Nat -> Nat

{-# BUILTIN NATURAL Nat #-}

-- Sum
sum : Nat -> Nat -> Nat
sum Zero y = y
sum (Succ x) y = Succ (sum x y)

test : sum 0 0 ≡ 0
test = ?
```

Error message:

```
agda2-parse-error
cannot read: IOTCM "C:/Users/Adolfo/Documents/AdolfoDocs/Computer Science/UU/Master/Thesis/repo/experiments/prelude.agda" NonInteractive Direct ( Cmd_auto 0 (Range [Interval (Pn (Just (mkAbsolute "C:/Users/Adolfo/Documents/AdolfoDocs/Computer Science/UU/Master/Thesis/repo/experiments/prelude.agda")) 755 38 10) (Pn (Just (mkAbsolute "C:/Users/Adolfo/Documents/AdolfoDocs/Computer Science/UU/Master/Thesis/repo/experiments/prelude.agda")) 758 38 13)]) "" )
```

# Error when using '\\' to introduce latex symbols

If you try to use '\\' before loading the file (`C-c C-l`) it results in the error below:

```
Connection not established error: Connection not established
    at Connector.getConnection (C:\Users\<user>\.atom\packages\agda-mode\lib\connector.js:130:19)
    at Commander.dispatch (C:\Users\<user>\.atom\packages\agda-mode\lib\commander.js:48:48)
    at HTMLElement.subscriptions.add.atom.commands.add (C:\Users\<user>\.atom\packages\agda-mode\lib\agda-mode.js:106:32)
    at CommandRegistry.handleCommandEvent (C:\Users\<user>\AppData\Local\atom\app-1.21.0\resources\app\src\command-registry.js:381:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\<user>\AppData\Local\atom\app-1.21.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\<user>\AppData\Local\atom\app-1.21.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\<user>\AppData\Local\atom\app-1.21.0\resources\app\src\window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (C:\Users\<user>\AppData\Local\atom\app-1.21.0\resources\app\src\window-event-handler.js:3:65)
```

**Comment by banacorn** [comment]
Thanks for the stack trace, the latex symbol problem should be resolved!

As for *Errors in Auto*, could you provide the **version of Agda** you are using? (try `agda --version`)
Because there are many versions of [the protocol](https://github.com/banacorn/agda-mode/wiki/Conversations-between-Agda-&-agda-mode) we need to handle.

**Comment by banacorn** [comment]
Hmm ... this is weird because agda-mode should be sending 
```... (intervalsToRange (Just (mkAbsolute ...``` 
instead of 
```... (Range [Interval (Pn (Just (mkAbsolute ...```
after v2.5.1

**Comment by aochagavia** [comment]
Are you able to reproduce the error?

**Comment by banacorn** [comment]
I can only reproduce the error by sending requests using [the protocol prior to v2.5.1](https://github.com/banacorn/agda-mode/wiki/Conversations-between-Agda-&-agda-mode#example-of-usage-of-range).

**Comment by aochagavia** [comment]
Weird. Maybe it has to do with the fact that I used to have an older version and updated short ago to `2.5.3`?

The content of the "internal state gibberish" field in the config is:

```
{  
   "connections":[  
      {  
         "guid":"c196decc-cc88-4456-877c-6c8d05383b39",
         "agda":{  
            "location":"C:/Users/<user>/AppData/Roaming/local/bin/agda.exe",
            "version":{  
               "raw":"2.5.1.1",
               "sem":"2.5.1-1"
            }
         }
      }
   ],
```

As you can see, there is a mismatch between my agda version and the version in that json blob. I just changed it to say `2.5.3` and it is working properly now! Thanks for your help.

**Comment by banacorn** [comment]
Yes, I think that's the problem! Thanks a lot!

**Comment by banacorn** [comment]
It turns out that the protocol of `give` did change in `v2.5.3`. :+1: 

https://github.com/agda/agda/commit/021e6d24f47bac462d8bc88e2ea685d6156197c4
