### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by marcosh** [banacorn/agda-mode#55]
I installed `agda` and I am able to use from my console. I added the `atom` extensions `language-agda` and `agda-mode`.

Still, when I try to compile an agda file, I get the following error message: 

```
ghc: createProcess: runInteractiveProcess: exec: does not exist (No
such file or directory)
```

I am not really an expert of ghc, so this could well be a trivial issue

**Comment by banacorn** [comment]
Interesting! 
Could you provide the version of `ghc` and `agda` you are running? And also the code you want to compile.
```bash
ghc -V
agda -V
```

I'm running `ghc-8.2.1` and `agda-2.5.3` and I can compile [the example provided by the manual](http://agda.readthedocs.io/en/latest/tools/compilers.html#ghc-backend) just fine!

**Comment by marcosh** [comment]
Thanks for your response. I realized that this is not a `agda-mode` issue. If I use the `--compile` option on the command line I get the same error message.

This is probably due to the fact that I installed `ghc` using `stack` and therefore I don't have a `ghc` command available (instead I have `stack exec ghc`).
Now I installed `ghc` globally and everything seems to work.
