### ISSUE TITLE
Loop?

### ISSUE THREAD

**Issue by jonaprieto** [banacorn/agda-mode#56]
Hi,

I have this literate Agda file (.lagda):

https://goo.gl/oJf2WX

When I try to type-check it, Atom get stuck suggesting to close the app (after 5min).
Nevertheless, using emacs it just type-check on the fly, 1sec.

**Comment by banacorn** [comment]
Issue reproduced! Thank you for reporting this!

**Comment by banacorn** [comment]
I've pinned down the source of the problem!

Temporary fix: **remove L930 - L970 from your `lagda` file** 😂

The code didn't take care of literate Agda files, so it would treat Latex code as Agda and try to parse the hell out of it. In this seemly non-terminating case, agda-mode was trying to find Agda comments in `L930 - L970` with regular expressions but somehow got overwhelmed.

**Comment by jonaprieto** [comment]
Thanks! @banacorn
