### ISSUE TITLE
Unicode input with two or more cursors

### ISSUE THREAD

**Issue by banacorn** [banacorn/agda-mode#59]
Posted by @jonaprieto at https://github.com/banacorn/language-agda/issues/13

-----

I use to replace text using ctrl+D to select the same matches for example.
But with the cursors that the atom puts, when I try to write some Unicode character,
what I got is that only in the last line (last match) the Unicode appears. Why?

For example, 
```
A
...
A
```

After selecting the As with two cursors (symbol |)

```
A|
...
A|
```

And if I try to type `\_1` instead of 

```
A₁
...
A₁
```
This is what I got
```
A₁
...
A_1
```

**Comment by jonaprieto** [comment]
With the last release 0.7.14 I have nothing

**Comment by banacorn** [comment]
Silly me, I forgot to merge the developing branch. 😂

**Comment by jonaprieto** [comment]
This is awesome! Thanks
