### ISSUE TITLE
Jump to Definition

### ISSUE THREAD

**Issue by banacorn** [banacorn/agda-mode#6]
pending atom [Support for mouse actions in “keymaps”?](https://discuss.atom.io/t/support-for-mouse-actions-in-keymaps/10867)

**Comment by PiotrJander** [comment]
How about a keyboard shortcut? Atom has the "Go to declaration" shortcut.

**Comment by banacorn** [comment]
Good point! Almost forgot about this feature that we've been longing for.

Should be just a step away from the functionality of *why in scope* (<kbd>C</kbd>+<kbd>c</kbd> <kbd>C</kbd>+<kbd>w</kbd>).

**Comment by jonaprieto** [comment]
Are you referring to the  C-C C-, and C-C-. in emacs?
If so, I'd be very glad to have this feature in a coming version.
It is essential.

**Comment by banacorn** [comment]
@jonaprieto did you mean `C-c C-,`  (goal type and context) and `C-c C-.` (goal type and inferred type)?

**Comment by jonaprieto** [comment]
@banacorn  Yes, that key shortcut, btw, is there any progress with this feature :-)
That's one of the reasons I always open at first emacs.

**Comment by banacorn** [comment]
I'll see if I can ship this in the next release!

**Comment by jonaprieto** [comment]
Thank you! this is definitely so essential. It's so annoying to use the scroll to search. :-(
