### ISSUE TITLE
Menu options

### ISSUE THREAD

**Issue by jonaprieto** [banacorn/agda-mode#60]
Is there any chance to put the following menu:

![image](https://user-images.githubusercontent.com/1428088/42641706-703aef64-85f5-11e8-9e00-f73c2feacf0e.png)

In the options of the menu (right-click on the mouse)?
![image](https://user-images.githubusercontent.com/1428088/42641741-83760942-85f5-11e8-97b5-711e144ea25c.png)

That will be very useful for some options!

**Comment by banacorn** [comment]
Yes! seems like it's totally doable: https://atom.io/docs/api/v0.188.0/ContextMenuManager.

I hope there's some way for a user to decide which command to be listed in the menu,
because as you can see, there are quite a lot of them.

**Comment by banacorn** [comment]
It turned out that having to many commands is not a problem, just cram them in our own sub-menu.

![image](https://i.imgur.com/QEn1oo4.png)

**Comment by jonaprieto** [comment]
With the last release 0.7.14 I have nothing

**Comment by banacorn** [comment]
Silly me, I forgot to merge the developing branch. 😂

**Comment by jonaprieto** [comment]
It works now, thanks a lot
