### ISSUE TITLE
Show the panel when open an agda file

### ISSUE THREAD

**Issue by jonaprieto** [banacorn/agda-mode#61]
It would be nice to have the panel docking as soon as we open an Agda file,
With some message like "Agda-mode loaded" or whatever. My point is the following.
I have a file which takes to compile almost one minute. Since I just opened the file and then
I typed C-C C-L to type-check the file, I don't know whether it's working or not. So, I sometimes got nervous because I don't know what's happening. When I got the panel, I see something at least.

**Comment by banacorn** [comment]
Do you want an Agda file to be loaded right after it is opened, or do you just want to see those type-checking messages running like in Emacs?

**Comment by jonaprieto** [comment]
> Do you want an Agda file to be loaded right after it is opened
No. That is not a good idea. 

This request is just concerned with **the first time you open the file**.

The current behavior:
You open the file, there is nothing in the panel docking because the file is not type-checked yet.
Then, the user may want to type-check the file and wait to see the result. 
That's is how it works now and it's fine. 

Now, my request is based on the following.

Imagine that you agda file has tons of code. You opened the file for the first time and you run the command to type-check it. At this point, you have to wait of course. But the user doesn't know if agda is effectively working or not because since it's the first time and the panel docking has not been opened yet.  So since the agda file takes considerable time type-checking, the user starts feeling 
desperate (xD) and start typying C-C C-L to see if something happen and so on.

The thing is we can avoid this just showing the panel as soon as the user open an agda file.
The panel can content a message like: "Agda-Mode waiting to type-check" or whatever. If the user
decide to type-check, they will know what's happening because for the panel we have now the 
![image](https://user-images.githubusercontent.com/1428088/42943993-beee5fb4-8b64-11e8-9980-2cf9ef26afdf.png)

I might be badly expresing this. Sorry.

**Comment by banacorn** [comment]
I see!!
