### ISSUE TITLE
Verbose Panel

### ISSUE THREAD

**Issue by jonaprieto** [banacorn/agda-mode#62]
A verbose panel would be useful in some cases.
Maybe letting the possibility to configure the level of verbosity, which
is the option in Agda, `---verbose N`.

**Comment by banacorn** [comment]
I remember there used to be a field in the settings where you can feed the options to Agda (like you would in the terminal), but somehow it's gone 😂😂😂.

Todo:
- [ ] Allow users to specify options in the settings 
- [ ] Address this in the documentation

**Comment by banacorn** [comment]
I got 8000+ lines of "Running Infos" with `--verbose=1` and crashed the whole editor.
Even if it doesn't crash the editor, cramming 8000+ lines of infos in a tiny panel wouldn't do any good.

I'll see if I can put them in a file (either virtual or in somewhere like `/var/`)

**Comment by markokoleznik** [comment]
Just a suggestion. Maybe it would be useful if a user can specify "logs" folder. That, and maybe some toast notification that the file "agda-output-20180726-070518.log" has been saved to "/User/username/path/to/agda/verbose". Does that make sense?

**Comment by banacorn** [comment]
That's a good idea!!

**Comment by banacorn** [comment]
I'm putting them in a temporary editor.
It's up to the user to decide what to do with it (saving it in a log folder or whatever)

![image](https://i.imgur.com/hv37PQo.png)

**Comment by jonaprieto** [comment]
How did you solve it?

**Comment by banacorn** [comment]
I dumped all running infos into a new temporary editor. To be more specific, it opens a new editor every time we hit `load`, appends to the previously opened editor otherwise. It's miserable but at least some what usable XD.

**Comment by banacorn** [comment]
Actually I never knew that "running infos" exists before you opened this issue, may I ask why would you need them?
