### ISSUE TITLE
Input for super-indexes doesn't work well

### ISSUE THREAD

**Issue by jonaprieto** [banacorn/agda-mode#63]
I might be doing something wrong but when I try to introduce
a super-index I just can't.

I type `\` + `ˆ`  or `\` + `ˆ`+ SPC then I just can't get the super intex.

If I just type `\` and use in the bottom panel that appears with the symbols I can.
Then I can put whaevert I want by choosing `^` followed by the number or whatever BUT clicking
with the mouse, which is so annoying. 

Any clue?

**Comment by banacorn** [comment]
It's working fine on my laptop, could it be input-method or keyboard-layout-related stuff?

**Comment by jonaprieto** [comment]
You're right.  It's working fine with "US"  instead of the US international option. weirdo.

![image](https://user-images.githubusercontent.com/1428088/43386796-04455e18-93e5-11e8-88a2-52edd47aa0e1.png)
