### ISSUE TITLE
\Tb should include other triangles

### ISSUE THREAD

**Issue by banacorn** [banacorn/agda-mode#66]
Typing `\Tb` should yield 4 different kinds of black triangles: `◀`, `▶`, `▲`, `▼` instead of just one.
```js
{"b":{">>":["◀","▶","▲","▼"]}}
```

Something's wrong with the input-method

**Comment by pi314** [comment]
4 directions of Doritos

**Comment by banacorn** [comment]
`◀ ◁ ▶ ▷ ▲ △ ▼ ▽ ◬ ◭ ◮`

🌮🌮🌮不客氣 🌮🌮🌮

**Comment by banacorn** [comment]
🌮🌮🌮🌮🌮🌮🌮🌮🌮🌮🌮🌮🌮
110b8fd happens to be the 1500th commit.
🌮🌮🌮🌮🌮🌮🌮🌮🌮🌮🌮🌮🌮
