### ISSUE TITLE
Cannot read property '0' of undefined in Atom

### ISSUE THREAD

**Issue by livecodealex** [banacorn/agda-mode#69]
I have run
```
sudo apt-get install ghc
sudo apt-get install agda
sudo apt-get install agda-mode
apm install agda-mode
apm install language-agda
```

And when I open a file (known to work) and then Ctrl-C and Ctrl-L it doesn't work

**Comment by banacorn** [comment]
Thanks for reporting this, can you provide a more detailed stack trace?

**Comment by livecodealex** [comment]
![agda-mode](https://user-images.githubusercontent.com/15053373/45640869-bb56c500-baab-11e8-994e-cf13708d3f3b.png)

**Comment by banacorn** [comment]
Can you provide the version of Agda you're using?

**Comment by livecodealex** [comment]
`agda --version` gives 2.5.3

**Comment by banacorn** [comment]
Closing this because I've rewritten the connecting mechanism with Reasonml/OCaml.
JS runtime errors like `Cannot read property '0' of undefined` should be gone for good.
