### ISSUE TITLE
How to accept unicode input without moving cursor?

### ISSUE THREAD

**Issue by buggymcbugfix** [banacorn/agda-mode#71]
Say I wanted to write `⟨⟨` as an identifier.

Typing `\` `<` `\` `<` results in `⟨\<`, so what I do is enter the following sequence of characters:

`\` `<` `[SPC]` `[BKSPC]` `\` `<`

Is there some key to accept the current input which would allow me not to have to space and backspace?

**Comment by buggymcbugfix** [comment]
PS: I tried <kbd>esc</kbd> but that doesn't do anything.

**Comment by buggymcbugfix** [comment]
PS': in the specific case of entering two consecutive non-Ascii characters, like above, it seems that I shouldn't even need to escape out of the special input mode, since <kbd>\</kbd> always terminates it. (?)

**Comment by buggymcbugfix** [comment]
Hey, I think at some point you mentioned that it may be possible to factor out the input method part of this package? I think this would be really useful for use in other contexts. Currently it only works in files with .agda extension. Is this something that's already possible and if not, how doable is this? I would love to help but I'm by no means a JS whizz.

**Comment by banacorn** [comment]
The picture I had in mind is to make this input method an extension ("Provider") of the [Autocomplete+ package](https://github.com/atom/autocomplete-plus). All we have to do is create a new package that work together with its [Provider API](https://github.com/atom/autocomplete-plus/wiki/Provider-API). However the UI will be a lot different from what we have in agda-mode (in case you are expecting anything).

**Comment by buggymcbugfix** [comment]
I don't really mind the UX of Autocomplete+. Is it possible to use the backslash with Autocomplete+ though? I tried making snippets that start with backslash and they don't seem to complete.

**Comment by banacorn** [comment]
I'll see if I have time to try this out this weekend!

**Comment by buggymcbugfix** [comment]
Let me know if you need any input/help. We would like to use this with [granule](https://github.com/granule-project/granule).

**Comment by banacorn** [comment]
You can now also exit the input method by pressing <kbd>RETURN</kbd> and <kbd>ESC</kbd>.
