### ISSUE TITLE
Unicode input issue

### ISSUE THREAD

**Issue by buggymcbugfix** [banacorn/agda-mode#72]
PS'': When I try to write `identityʳ`, when I do `\` `^` `r` after `identity`, I get this:
<img width="84" alt="screen shot 2018-10-16 at 15 12 13" src="https://user-images.githubusercontent.com/17603372/47022670-eb9a8d80-d155-11e8-8636-5eb5df6121ea.png"> I then have to do right arrow on my keyboard to get `identityʳ`. Is this a bug or some sort of font issue?

**Comment by erydo** [comment]
This is a bug, I encounter this too when I do it for `\^r` or `\^l`. I end up having to manually copy and paste it.

**Comment by erydo** [comment]
Ok, I have not tracked this issue down but I can provide some additional information and repro steps. I noticed something interesting: _clicking_ the symbol in the input method correctly inserts the character.

| Key Sequence | UI State
:------:|:----
| <kbd>\\</kbd> | <img width="140" alt="text-0" src="https://user-images.githubusercontent.com/447615/65560675-94786d80-df0d-11e9-8c69-2ebfb95445e5.png"> <br> <img width="1388" alt="im-0" src="https://user-images.githubusercontent.com/447615/65560772-e6b98e80-df0d-11e9-901d-b5dafedc6a5d.png">
| <kbd>\\</kbd><kbd>^</kbd> | <img width="140" alt="text-1" src="https://user-images.githubusercontent.com/447615/65560695-a823d400-df0d-11e9-818b-9c834d10d066.png"> <br> <img width="1388" alt="im-1" src="https://user-images.githubusercontent.com/447615/65560778-ed480600-df0d-11e9-9c69-72ee048b8f89.png">
| <kbd>\\</kbd><kbd>^</kbd><kbd>r</kbd> | <img width="140" alt="text-2" src="https://user-images.githubusercontent.com/447615/65560736-c1c51b80-df0d-11e9-82a4-81bc62e4603e.png"> <br> <img width="1388" alt="im-2" src="https://user-images.githubusercontent.com/447615/65560783-f33de700-df0d-11e9-901b-a46223623a34.png">
| <kbd>\\</kbd><kbd>^</kbd><kbd>r</kbd> (Hover) | <img width="140" alt="text-3" src="https://user-images.githubusercontent.com/447615/65560727-ba9e0d80-df0d-11e9-84f4-ac6db2a5ca50.png"> <br> <img width="1388" alt="im-3" src="https://user-images.githubusercontent.com/447615/65560787-f89b3180-df0d-11e9-8da2-dd644645fbdf.png">
| <kbd>\\</kbd><kbd>^</kbd><kbd>r</kbd> (After click) | <img width="140" alt="text-5" src="https://user-images.githubusercontent.com/447615/65560754-d30e2800-df0d-11e9-8ddd-4207889d1587.png"> <br> <img width="1388" alt="im-5" src="https://user-images.githubusercontent.com/447615/65560799-051f8a00-df0e-11e9-8af5-588801759c0d.png">

If I select those squares (which select as a single character), copy the value, and paste into `xxd`:
```sh
pbpaste | xxd -
```
The result is:
```
00000000: 79e2 8397                                y...
```
Which is `79` (_y_) plus a [combining character `e2 8397` (_COMBINING RIGHT ARROW ABOVE_)] (https://www.fileformat.info/info/unicode/char/20d7/index.htm).

The result of the entire editor text is:
```
00000000: 6964 656e 7469 7479 e283 97ca b3         identity.....
```
Note that the `cab3` is the Unicode of the intended `ʳ` character.

Interestingly, when I just copied from Atom and pasted into vim, it looks like so:

<img width="92" alt="Screen Shot 2019-09-24 at 9 07 58 PM" src="https://user-images.githubusercontent.com/447615/65561270-d60a1800-df0f-11e9-83a0-d0e2bae3e762.png">

Which shows the arrow combining character more clearly.

**Comment by erydo** [comment]
Additional info: This does not appear to be a font issue (at least, not strictly). The text shows up visibly in Vim and my console and they're the same font as in Atom, and changing Atom's font between several common ones like Menlo, Consolas, etc. does not fix the issue.

I've confirmed that Atom is set to UTF-8. I'm beginning to think this might be a purely Atom/Chrome issue (wrt to correctly displaying the combining right arrow). For example, I see squares on this page in Chrome: https://tex.stackexchange.com/questions/171356/using-unicode-combining-right-arrow-above-to-generate-vector-command

So perhaps the "bug" here is just that agda-mode attempts to use that character, which it should reasonably be allowed to do. And the secondary cause is that it _prefers_ that character to the intended superscript `r`.

**Comment by banacorn** [comment]
Wow, didn't realize that the problem is that deep.

I'm currently working on refactoring and writing tests for the unicode input, and I'm planning to fix (or workaround, in this case) all related issues along the way.

**Comment by banacorn** [comment]
All 4 `^r` symbols can be displayed without much problem in Atom/Chrome when placed standalone. But some are problematic (boxes) when combined with some other characters:

standalone | unicode hex | combined | unicode hex 
----------- | ------------ | ---------- | ------------
`⃗ ` | 20d7 | `a⃗` | 61 20d7
`⃑`  | 20d1 | `a⃑` | 61 20d1
`⃕`  | 20d5 | `a⃕` | 61 20d5
`ʳ` | 2b3 | `aʳ` | 61 2b3

Because all these 4 symbols share the same sequence `^r`, they appear as "candidates" as seen in the bottom right. And the first candidate would be displayed as some kind of preview on the text editor. This explains the boxes you are seeing when you type `^r`.

You should see the displayed preview changing (not in this case as they all appear box-ish except for the last) as you navigate through the candidates (by pressing the arrow keys on your keyboard).

I suppose that `ʳ` is the most wanted symbol among these 4 symbols. 
I think placing `ʳ` as the first candidate would solve most of our problems.

**Comment by banacorn** [comment]
A more general way of solving this.
![Extending keymap](https://i.imgur.com/olyozuf.png)
