### ISSUE TITLE
Spaces break the executable path in Windows

### ISSUE THREAD

**Issue by dylanbraithwaite** [banacorn/agda-mode#75]
It seems like spaces in the executable path aren't being properly escaped in Windows. In particular I couldn't find a way to make `C:\Program Files\Haskell\bin\agda.exe` work as a path. The plugin reports
```
Found something at "C:\Program Files\Haskell\bin\agda.exe" but it doesn't seem quite right:
Command failed: C:/Program Files/Haskell/bin/agda.exe
'C:/Program' is not recognized as an internal or external command, operable program or batch file.
```

**Comment by banacorn** [comment]
Thanks for reporting this!

**Comment by Supernerd11** [comment]
Fixed this by adding quotes around the path, i.e `"C:\Program Files\Haskell\bin\agda.exe"` insted of `C:\Program Files\Haskell\bin\agda.exe`.

**Comment by dylanbraithwaite** [comment]
I'm almost certain I had tried adding quotation marks without any change before opening this issue. I eventually gave up trying to install the plugin after running into a similar issue to #68 (using a path without spaces for agda) but I'll reinstall tomorrow and see if quoting the path makes any difference now. Thanks!

**Comment by banacorn** [comment]
I was able to reproduce this issue, and the workaround provided by @Supernerd11 (adding quotes around the path) also worked as well.
