### ISSUE TITLE
Case-splitting gives error "Cannot read property 'push' of undefined" on Windows

### ISSUE THREAD

**Issue by Supernerd11** [banacorn/agda-mode#76]
Whenever I try to case-split in a hole, it "disconnects" from agda with the error `Cannot read property 'push' of undefined`.

I can load the file, use auto, see context, etc; however, when there is a type error or when i try to case split it gives back `Cannot read property 'push' of undefined`.

I'm not sure if this is a duplicate issue, it might very well be, and in that case I'm very sorry.

**Comment by banacorn** [comment]
Sorry that I was so occupied that I missed this issue by 2 weeks.

The whole project is now under rewrite from JS to OCaml, the current version is kinda in between.
So it looks like something bad happened with the interop.

**Comment by razvan-panda** [comment]
@banacorn when will a fix be released?

**Comment by razvan-panda** [comment]
@banacorn The extension version I have is 0.8.6 and it manifests the bug
Was there a new release?

**Comment by banacorn** [comment]
The next version will be 0.8.7, It should be released within 12 hours (after I got my hands on a Windows again).

**Comment by razvan-panda** [comment]
@banacorn Tested and it works. Thank you very much! 💯
