### ISSUE TITLE
Custom unicode character codes

### ISSUE THREAD

**Issue by jaywunder** [banacorn/agda-mode#79]
Hey! Thank you for maintaining this package.

My team is using agda, and we have our own character codes for certain unicode characters.  I'm wondering if you have any suggestions for how would be best for me to add custom character codes.

I notice you're using a Trie data structure so I wonder what you did you use to create your static trie file?  I think a nice short term solution is for me to use my own trie created from our config.

Thank you!

**Comment by banacorn** [comment]
[This](https://github.com/banacorn/keymap) is the repo where the trie was generated.
It's written in Haskell. The source code looks bad, but it shouldn't be difficult to add your own characters.

After you have generated your own copy of the keymap, replacing the original one sitting in the package and reload everything should work!

**Comment by banacorn** [comment]
Seems like there's no need of modifying the code or anything.
All you have to do is just drop your custom characters [like this](https://github.com/banacorn/keymap/blob/master/assets/alpha-numeric.ext) in `assets/` and run the program to generate the new keymap! :D

**Comment by jaywunder** [comment]
Thank you for helping! I'll look using this as the short term solution 😄 

Would you be open to a PR that allows for overrides and generates a trie from a config given by the user?  That would make make this functionality builtin.

**Comment by banacorn** [comment]
I think generating a trie from some config on site would be a bit too much for now, as I'm currently rewriting this project from TypeScript to Reason (OCaml). 

But it's a good functionality to have, we shall leave this issue open until it's implemented.

In the meanwhile, perhaps allowing the user to custom the path to some generated trie in the config would be a good idea?

**Comment by markokoleznik** [comment]
Hey, a bit offtopic but I’m really curious...
Is there any special reason why rewrite it in Reason (pun intended 😀)?
Didn’t you already rewrite (at least part of the program) from CoffeeScript to TypeScript? 😂
Other than that, great job!

**Comment by jaywunder** [comment]
@banacorn, I'll add a path to the trie in the config, that's a good temp solution until you finish the rewrite.

**Comment by banacorn** [comment]
@markokoleznik because I still get errors like `Uncaught TypeError: undefined is not a function` 💢,
and then Reason caught my attention. Gosh I hate JavaScript (and TypeScript) so much.

**Comment by banacorn** [comment]
Voila

![Extending keymap](https://i.imgur.com/olyozuf.png)

**Comment by jaywunder** [comment]
wow!! great work! this looks fantastic

**Comment by jaywunder** [comment]
Hey has this feature been published yet? It seems to be in the changelog for the package but this is what my settings looks like for agda-mode:

![image](https://user-images.githubusercontent.com/6374335/68143691-fca07300-feff-11e9-9d04-279c5d47390e.png)

**Comment by banacorn** [comment]
Gosh you are right, sorry I forgot to rebuild the distribution bundle so basically the `v0.9.9` update is completely the same as `v0.9.8` 😅

**Comment by banacorn** [comment]
Please update to `v0.9.10` and you should see something new 😅
