### ISSUE TITLE
renaming open files

### ISSUE THREAD

**Issue by Zambonifofex** [banacorn/agda-mode#84]
It seems like, whenever I rename an open file and try to load it, the package reports: `getModificationTime:getFileStatus: does not exist (No such file or directory)`

It’s easy to work around this by closing the file (either before or after renaming), and then opening it again (only after renaming).

**Comment by banacorn** [comment]
Fixed in the `ocaml` branch, please wait until it lands on `master` :D.

**Comment by banacorn** [comment]
Landed in `v0.9.0`!
