### ISSUE TITLE
[dev] package-lock.json and yarn.lock are in .gitignore

### ISSUE THREAD

**Issue by erydo** [banacorn/agda-mode#93]
https://github.com/banacorn/agda-mode/blob/921460aaadd8476203710369906578451a8c9b24/.gitignore#L5
https://github.com/banacorn/agda-mode/blob/921460aaadd8476203710369906578451a8c9b24/.gitignore#L13

One of these lockfiles should be checked in. (I prefer Yarn, but I believe later versions of npm (>= 5) work ok).

Without it, it's impossible for other developers to recreate the same set of set of transitive dependencies as the official package.

Having the lock file checked in will also allow you to stop committing the compiled source under `lib/`, since those builds will be reproducible.

I'm happy to create a PR that does this, but since the lock file is missing, my machine does not install the exact same transitive dependencies as @banacorn is using to build the files under `lib/`; it would be better for that lock file to represent the current state. @banacorn would you be able to share or generate it?

**Comment by banacorn** [comment]
I'm not sure if I'm doing it right, here's what I've done to generate the lockfiles:

For `package-lock.json`:
1. `rm -rf node_modules`
2. `npm install`

For `yarn.lock`:
1. `rm -rf node_modules`
2. `yarn`

**Comment by erydo** [comment]
Awesome! Thank you!
