### ISSUE TITLE
Input method gets stuck if text cursor is moved

### ISSUE THREAD

**Issue by erydo** [banacorn/agda-mode#94]
It would be great if the input mode could abort on <kbd>Esc</kbd> and if the cursor is manually repositioned.

There are currently (0.8.10) two related problems.

If you start the input mode (like <kbd>\\</kbd> <kbd>x</kbd> ) and then click elsewhere, input mode will never recover without clicking one of the toolbar buttons or moving the cursor back to its original position.

If you're using `vim-mode-plus`, then the toolbar gets stuck open _all_ the time, because the vim "Normal" mode (for moving the cursor) is entered by pressing <kbd>Esc</kbd>. I'd expect this to abort the input mode, but it doesn't. So if you press <kbd>Esc</kbd> while entering an agda character, you have to then re-enter insertion mode, press <kbd>Space</kbd> or something to flush `agda-mode`'s character, and then press <kbd>Esc</kbd> to go back to Normal mode as you originally intended.

**Comment by erydo** [comment]
Reading through the issues, this is probably also related to this: #71

**Comment by banacorn** [comment]
Thank you for reporting this!
Now the input method should deactivate when:
1. <kbd>Esc</kbd> got pressed
2. cursor is out of range

This patch will come with the next big-big-everything-got-rewritten release, so it might take a little bit longer.
