### ISSUE TITLE
Funny display of backslashes in error message

### ISSUE THREAD

**Issue by omega12345** [banacorn/agda-mode#95]
If I try to load this file:

```
module EscapedBackslash where
open import Agda.Builtin.Char
open import Agda.Builtin.List
open import Agda.Builtin.String

s : List Char
s = "\\"
```

I get the following error message:

```
String != List Char of type Set
when checking that the expression "//" has type List Char
```

This behaviour is caused by line 111 in Emacs__Parser.re :

```
let result =
      ref(string |> Js.String.replaceByRe([%re "/\\\\\\\\/g"], "/"));
```

I can't fix it myself because I have no Windows system to test it on.

**Comment by banacorn** [comment]
Thanks for reporting this.

Hmm, escape characters in string quotes need to be escaped somehow.
To be honest I still can't wrap my head around that big pile of backslashes  `[%re "/\\\\\\\\/g"]`  hehe
