### ISSUE TITLE
Loading an identifier starting with a `?` accidentally creates a hole

### ISSUE THREAD

**Issue by hakandingenc** [banacorn/agda-mode#96]
Loading an identifier starting with the `?` character accidentally creates a hole instead of parsing it as is. For example,
```
data MBool : Set where
   TT : MBool
   FF : MBool
   ?? : MBool
```
turns into
```
data MBool : Set where
   TT : MBool
   FF : MBool
   {!   !}? : MBool
```
and
```
?? : Set -> Set
?? x = x
```
turns into 
```
?? : Set -> Set
{!   !}? x = x
```
leaving the first identifier unchanged. It affects identifiers like `?e`, `???eeee`, but not the ones that only include `?` instead of starting with it as in `e?`.

**Comment by banacorn** [comment]
Wow, never thought that we can use `?` as part of a name!
