### ISSUE TITLE
Failure to load on Windows 10

### ISSUE THREAD

**Issue by mrakgr** [banacorn/agda-mode#98]
Just now I've done a fresh install of the Haskell platform (8.6.5), installed Agda using `cabal update` and `cabal install Agda`, and now I am trying to load the `hello.agda` file.

```
module hello where
open import IO

main = run (putStrLn "Hello, World!")
```

The `Connection To Agda` window gives me the following error.

```
Found something at "C:/Users/Marko/AppData/Roaming/cabal/bin/agda" but it doesn't seem quite right. Command failed: C:/Users/Marko/AppData/Roaming/cabal/bin/agda
```

It did not recognize that Agda 2.6.0 is already in PATH so I had it put in by hand. It seems that Agda works fine from the command line (though it complains that it can't find the IO library). Just now I have installed both Agda plugins for Atom and the editor is up to date.

Also I've had Agda + Emacs installed 2.5 years ago that I've never used along with old Haskell, so there might be still be some old settings lurking somewhere, but I am decently sure that I removed that crud properly even if some of it was by hand.

What should I do here?

**Comment by mrakgr** [comment]
I can confirm that this is the same issue as [this one](https://github.com/banacorn/agda-mode/issues/97). Thank you @lsti115. I haven't got it to run properly just yet though. Let me see if I can get the standard library to work.

**Comment by mrakgr** [comment]
I had to clone it from [the repo](https://github.com/agda/agda-stdlib) and then use `cabal install` in its directory. Then I got stuck for a bit as that was not the whole procedure.

Surprisingly, following the instructions [here works](https://agda.readthedocs.io/en/latest/tools/package-system.html). I was skeptical as the `C:\Users\Marko\AppData\Roaming\agda` directory did not even exist and there is a core library in a completely different place courtesy of cabal, but I did need to create it and the two files. With the standard library in tow, the program compiles and runs successfully. I had no idea Agda could even compile executable programs till now. I had the impression it was a proof assistant.

Now I get this error when I try to load in Atom.

```
agda2-parse-error
cannot read: IOTCM ""E:/Theorem Proving/Agda/hello.agda"" NonInteractive Direct ( Cmd_load ""E:/Theorem Proving/Agda/hello.agda"" [] )
```

I got this even before I installed the library and I thought this might be due to not being able to find it, but I guess not. What should I do here?

**Comment by banacorn** [comment]
Thanks for reporting this.
That `""E:/Theorem Proving/Agda/hello.agda""` double-double-quote looks suspiciously suspicious.

**Comment by mrakgr** [comment]
Nice spot. It seems the plugin cannot handle empty spaces in paths for some reason. Once I renamed `Theorem Proving` to `TheoremProving` it started working. Right now the plugin feels a bit sluggish, but otherwise things seem to be fine. Thank you for the help.

**Comment by banacorn** [comment]
I will reopen this issue until those problem got solved

**Comment by marklemay** [comment]
I seem to also be having this problem.  

when I run `ctrl-l crl-n` in my test file
```
module example where

data B : Set where
  tt : B
  ff : B
```

I get 
```
1 errors arisen when trying to parse the following text responses from agda:

cannot read: IOTCM "C:\ce\example.agda" NonInteractive Direct ( Cmd_load "C:\ce\example.agda" [] )
```

My old emacs mode from a previous install seems to work.
and 
```
C:\ce>agda Example.agda
Checking example (C:\ce\example.agda).
```
versions:
agda, 2.6.0.1
atom 1.37.0
agda-mode 0.9.0?

and I turned on the unicode trick here https://github.com/banacorn/agda-mode/issues/97#issuecomment-491516453

Is there's anything I can do to track this issue down?

**Comment by marklemay** [comment]
After a little hacking I can replicate this in my console
```
C:\ce>C:\Users\Mark\AppData\Roaming\cabal\bin\agda --interaction
Agda2> IOTCM "C:\ce\example.agda" NonInteractive Indirect ( Cmd_load "C:\ce\example.agda" [] )
cannot read: IOTCM "C:\ce\example.agda" NonInteractive Indirect ( Cmd_load "C:\ce\example.agda" [] )
```
